Created CICD pipeline.
LondheShubham153/Springboot-BankApp pull request #2
Opened 2024-11-11 15:02 UTC by joakim077

Added guide to create CICD pipeline and configure nginx as a proxy server, also added SSL encryption for secure HTTPS communication.

2024-11-12 13:13 UTC, LondheShubham153 requested changes
@joakim077 great work, 
there are a few suggestions from @coderabbit 
please add them as well

2024-11-12 13:48 UTC, joakim077 commented
@LondheShubham153 sure sir

2024-11-17 06:02 UTC, joakim077 commented on cicd.md
> +        - Install Docker and docker-compose:V2 on worker node and add the user who is executing the Jenkins job into the docker group. because we are going to deploy application in worker node itself
yes

2024-11-17 06:46 UTC, joakim077 commented on cicd.md
> +        - Poll: periodically monitor the repository and if any changes are detected, build Job.
yes

2024-11-17 06:47 UTC, joakim077 commented on cicd.md
> +- Pull image from docker hub and deploy application using docker compose .
provide a template

2024-11-19 13:37 UTC, LondheShubham153 approved these changes

2024-11-19 13:37 UTC, merged